[project]
name = "github-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "pathlib2>=2.3.7.post1",
    "pydantic>=2.11.9",
    "python-magic-bin>=0.4.14",
]
